---
- name: Converge
  hosts: all
  become: true
  vars:
    patroni_etcd_hosts: "{{ ansible_default_ipv4.address }}:2379"
    patroni_bootstrap_pg_hba:
      - { type: "host", database: "replication", user: "{{ patroni_replication_username }}", address: "{{ ansible_default_ipv4.address }}/0", method: "md5"}
      - { type: "host", database: "replication", user: "{{ patroni_replication_username }}", address: "127.0.0.1/32", method: "md5"}
      - { type: "host", database: "all", user: "all", address: "0.0.0.0/0", method: "md5"}
    patroni_postgresql_config_dir: "/etc/postgresql/{{ patroni_postgresql_version }}/{{ patroni_scope }}"
    #ansible_host: "127.0.0.1"

  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=yes
      changed_when: false

  roles:
    - role: geerlingguy.postgresql
    - role: igor_nikiforov.etcd
    - role: patroni
