---
- name: Install system packages for patroni
  package:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
    update_cache: yes
  with_items:
    - "{{ patroni_system_packages }}"
  when: patroni_install_from_pip

- name: Install pip packages for patroni
  pip:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
    umask: "{{ item.umask }}"
    executable: "{{ item.executable }}"
  with_items:
    - "{{ patroni_pip_packages }}"
  when: patroni_install_from_pip
