---
#- include_tasks: variables.yml

- import_tasks: install.yml

- import_tasks: configure.yml

- name: Start handlers at role end
  meta: flush_handlers

- name: Ensure patroni is running
  systemd:
    name: patroni.service
    state: started
    daemon_reload: yes
    enabled: yes
  changed_when: false
