---
etcd_version: "3.4.13"

etcd_user: "etcd"

etcd_group: "etcd"

etcd_conf_dir: "/etc/etcd"

etcd_service_enabled: True

etcd_service_state: "started"

etcdctl_output_format: "table"

etcd_config:
  name: "{{ ansible_facts.hostname }}"
  data-dir: "/var/lib/etcd/data"
  wal-dir: "/var/lib/etcd/wal"
  initial-advertise-peer-urls: "http://{{ ansible_host }}:2380"
  initial-cluster-token: "token"
  initial-cluster-state: "new"
  advertise-client-urls: "http://{{ ansible_host }}:2379"
  listen-client-urls: "http://{{ ansible_host }}:2379,http://127.0.0.1:2379"
  listen-peer-urls: "http://{{ ansible_host }}:2380,http://127.0.0.1:2380"
  log-level: "debug"
  logger: "zap"
  initial-cluster: "{{ ansible_facts.hostname }}=http://{{ ansible_host }}:2380,"
  enable-grpc-gateway: true
